name: Regression Test Docker Action

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches-ignore: [master]

jobs:
  Sanity_Check:
    runs-on: ubuntu-latest
    name: A job to run regression tests
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: pytorch_action step
      id: pytorch_action
      uses: jdk-maxim/pytorch-docker-regression-action@master
      with:
        file-to-run: ".github/regression_test_scripts/regression_test_action.sh"
    # Use the output from the `pytorch_action` step
    - name: File run status
      run: echo "File run status is ${{ steps.pytorch_action.outputs.file_run_status }}"
    - name: File run status eval
      run: exit ${{ steps.pytorch_action.outputs.file_run_status }}
